<?php

namespace Bs\RouteBundle\Repository;

use Bs\RouteBundle\Entity\Route;
use Doctrine\ORM\EntityRepository;

/**
 * RouteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository
{
    /**
     * @param $filter
     * @return Route[]
     */
    public function findFilter($filter)
    {
        $stations = $this->createQueryBuilder('r')
            ->join('r.from', 'f')
            ->join('r.to', 't')
            ->where('f.city LIKE :filter')
            ->orWhere('f.region LIKE :filter')
            ->orWhere('t.city LIKE :filter')
            ->orWhere('t.region LIKE :filter')
            ->setParameter('filter', '%'.$filter.'%')
            ->getQuery()
            ->getResult();

        return $stations;
    }


}
