<?php

namespace Bs\RouteBundle\Repository;

use Bs\RouteBundle\Entity\Route;
use Bs\RouteBundle\Entity\RouteStation;
use Doctrine\ORM\EntityRepository;

/**
 * RouteStationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RouteStationRepository extends EntityRepository
{
    /**
     * @param Route $route
     * @return RouteStation[]
     */
    public function findRouteStations($route)
    {
        $stations = $this->createQueryBuilder('r')
            ->where('r.route = :route')
            ->orderBy('r.position', 'ASC')
            ->setParameter('route', $route)
            ->getQuery()
            ->getResult();

        return $stations;
    }
}
