# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    form.type.model.search_entity:
        class: Bs\AppBundle\Form\SearchType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - {name: form.type, alias: search_route}

    app.mailer:
            class: AppBundle\Mailer\Mailer
            arguments: ['@mailer','@twig','%mailer_params%']
