<?php

namespace Bs\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CardRepository extends EntityRepository
{
}
