<?php

namespace Bs\StationBundle\Repository;

use Bs\StationBundle\Entity\Station;
use Doctrine\ORM\EntityRepository;

/**
 * StationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class StationRepository extends EntityRepository
{

    /**
     * @param $filter
     * @return Station[]
     */
    public function findFilter($filter)
    {
        $stations = $this->createQueryBuilder('s')
            ->join('s.location', 'l')
            ->where('s.name LIKE :filter')
            ->orWhere('l.city LIKE :filter')
            ->orWhere('l.region LIKE :filter')
            ->setParameter('filter', '%'.$filter.'%')
            ->getQuery()
            ->getResult();

        return $stations;
    }

    /**
     * @param $filter
     * @param $id
     * @return Station[]
     */
    public function findLocationStationsFilter($filter, $id)
    {
        $stations = $this->createQueryBuilder('s')
            ->join('s.location', 'l')
            ->where('l.id = :id')
            ->andWhere('s.name LIKE :filter OR l.city LIKE :filter OR l.region LIKE :filter OR l.region LIKE :filter')
            ->setParameter('filter', '%'.$filter.'%')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $stations;
    }

}
