<?php

namespace Bs\DriverBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DriverRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository
{
}
